name: Bug report
description: Report bugs with the engine here
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: "Describe your bug here."
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: "Steps to reproduce this bug."
    validations:
      required: true

  - type: textarea
    id: terminal
    attributes:
      label: "Command Prompt/Terminal logs"
      render: bash
    validations:
      required: false

  - type: dropdown
    id: modding
    attributes:
      label: "Have you modded the build?"
      options:
        - Yes, at Source Code level
        - Yes, using Mods
        - No
    validations:
      required: true

  - type: input
    id: buildsummary
    attributes:
      label: "If you edited anything in this build, mention or summarize your changes."
      placeholder: "I edited ClientPrefs.hx and tried to add a new setting"
    validations:
      required: false

  - type: dropdown
    id: btarget
    attributes:
      label: "What is your platform?"
      options:
        - "Windows"
        - "Linux"
        - "MacOS"
        - "Android"
        - "iOS"
        - "Not in this list (WILL BE CLOSED)"
    validations:
      required: true
